[package]
license = "MIT"
description = "Reimplementation of GitHub file paths pattern matcher" # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#patterns-to-match-file-paths
homepage = "https://anttiharju.dev/compare-changes/"
repository = "https://github.com/anttiharju/compare-changes"
readme = "docs/README.md"
name = "compare-changes"
version = "0.1.27"
edition = "2021"
keywords = ["glob", "github-actions", "path", "pattern-matching", "filter"]
categories = ["command-line-utilities", "parser-implementations"]
include = [
    "src/**",
    "tests/**",
]

[dependencies]
anstyle = "1.0.13"
clap = { version = "4.5.53", features = ["cargo"] }
serde_json = "1.0.145"
serde_yaml = "0.9.34"
tempfile = "3.23.0"

[dev-dependencies]
assert_cmd = "2.1.1"
