[package]
license = "MIT"
description = "Reimplementation of GitHub file paths pattern matcher" # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#patterns-to-match-file-paths
homepage = "https://anttiharju.dev/compare-changes/"
repository = "https://github.com/anttiharju/compare-changes"
readme = "docs/README.md"
name = "compare-changes"
version = "0.7.12"
edition = "2021"
keywords = ["glob", "github-actions", "path", "pattern-matching", "filter"]
categories = ["command-line-utilities", "parser-implementations"]
include = [
    "src/**",
    "tests/**",
]

[dependencies]
anstyle = { version = "1.0.13", optional = true }
chumsky = "0.12.0"
clap = { version = "4.5.53", features = ["cargo", "derive"], optional = true }
regex = "1.12.2"
serde_json = { version = "1.0.148", optional = true }
serde_yaml = { version = "0.9.34", optional = true }
tempfile = { version = "3.24.0", optional = true }

[features]
default = []
cli = ["anstyle", "clap", "serde_json", "serde_yaml", "tempfile"]
clap = ["dep:clap"]

[[bin]]
name = "compare-changes"
required-features = ["cli"]

[dev-dependencies]
assert_cmd = "2.1.1"
