name: semver-label
description: "Determines semantic version bump from PR labels"
inputs:
  require:
    description: "Whether to fail upon missing semver label"
    default: "true"
    required: false
  error-message:
    description: "Message to echo upon failure"
    required: false
    default: "PR must have exactly one of the following labels: major-release, minor-release, patch-release"
runs:
  using: "composite"
  steps:
    - name: Get labels
      id: label
      uses: anttiharju/actions/get-labels@v0

    - name: Check for major-release label
      id: major-release
      uses: anttiharju/actions/require-label@v0
      with:
        labels: ${{ steps.label.outputs.names }}
        name: "major-release"
        error-message: ${{ inputs.error-message }}

    - name: Check for minor-release label
      id: minor-release
      uses: anttiharju/actions/require-label@v0
      with:
        labels: ${{ steps.label.outputs.names }}
        name: "minor-release"
        error-message: ${{ inputs.error-message }}
        fail-on-match: ${{ steps.major-release.outputs.match }}

    - name: Check for patch-release label
      id: patch-release
      uses: anttiharju/actions/require-label@v0
      with:
        labels: ${{ steps.label.outputs.names }}
        name: "patch-release"
        error-message: ${{ inputs.error-message }}
        fail-on-match: ${{ steps.minor-release.outputs.match == 'true' || steps.major-release.outputs.match == 'true' }}

    - if: ${{ steps.major-release.outputs.match == 'false' && steps.minor-release.outputs.match == 'false' && steps.patch-release.outputs.match == 'false' }}
      id: fail
      name: Fail if no semver label matched
      shell: bash
      env:
        REQUIRE: ${{ inputs.require }}
        MSG: ${{ inputs.error-message }}
      run: |
        $GITHUB_ACTION_PATH/fail.sh

    # This is not baked into output value to avoid falsely setting release type if a step fails
    - if: steps.fail.outputs.skipped != 'true'
      name: Set output
      id: release
      shell: sh
      env:
        type: ${{ steps.major-release.outputs.match == 'true' && 'major-release' || steps.minor-release.outputs.match == 'true' && 'minor-release' || steps.patch-release.outputs.match == 'true' && 'patch-release' }}
      run: |
        echo "type=$type" >> "$GITHUB_OUTPUT"

    - name: Parse latest release
      id: latest
      shell: sh
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        $GITHUB_ACTION_PATH/latest.sh

    - if: steps.fail.outputs.skipped != 'true'
      name: Bump version
      id: bump
      shell: bash
      env:
        TYPE: ${{ steps.release.outputs.type }}
        MAJOR_RELEASE: ${{ steps.latest.outputs.major-release || 'no-major' }}
        MINOR_RELEASE: ${{ steps.latest.outputs.minor-release || 'no-minor' }}
        PATCH_RELEASE: ${{ steps.latest.outputs.patch-release || 'no-patch' }}
      run: |
        $GITHUB_ACTION_PATH/bump.sh

    - if: steps.fail.outputs.skipped != 'true'
      name: Log next version
      shell: sh
      env:
        version: ${{ steps.bump.outputs.version }}
      run: |
        echo "next=$version"
outputs:
  version:
    description: "Next semantic version"
    value: "${{ steps.bump.outputs.version }}"
  type:
    description: "Type of semantic version bump"
    value: ${{ steps.release.outputs.type }}
