name: "Commit release"
description: "Creates a release commit"
inputs:
  version:
    description: "Release version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create release commit
      env:
        version: ${{ inputs.version }}
      shell: sh
      run: |
        git reset --hard && git clean -df
        toml set Cargo.toml package.version "$version" > Cargo.toml.tmp && mv Cargo.toml.tmp Cargo.toml
        toml set Cargo.lock package.version "$version" > Cargo.lock.tmp && mv Cargo.lock.tmp Cargo.lock
    - name: Commit changes
      uses: anttiharju/actions/commit-changes@v0
      with:
        committer: "${{ github.actor }}[bot]"
        message: ${{ inputs.version }}
        token: ${{ steps.generate.outputs.token }}
