# CC=".release/.zcc/aarch64-macos.sh" cargo build --target aarch64-apple-darwin
[target.aarch64-apple-darwin]
linker = ".release/.zcc/aarch64-apple-darwin.sh"

# CC=".release/.zcc/x86_64-linux-gnu.sh" cargo build --target x86_64-unknown-linux-gnu
[target.x86_64-unknown-linux-gnu]
linker = ".release/.zcc/x86_64-linux-gnu.sh"

# CC=".release/.zcc/aarch64-linux-gnu.sh" cargo build --target aarch64-unknown-linux-gnu
[target.aarch64-unknown-linux-gnu]
linker = ".release/.zcc/aarch64-linux-gnu.sh"
