# TARGET=aarch64-apple-darwin CC="./.release/.helpers/zcc.sh" cargo build --target "$TARGET"
[target.aarch64-apple-darwin]
linker = "./.release/.helpers/zcc.sh"

# TARGET=x86_64-unknown-linux-gnu CC="./.release/.helpers/zcc.sh" cargo build --target "$TARGET"
[target.x86_64-unknown-linux-gnu]
linker = "./.release/.helpers/zcc.sh"

[target.aarch64-unknown-linux-gnu]
linker = "./.release/.helpers/zcc.sh"
