[target.aarch64-apple-darwin]
linker = "./.release/.helpers/zcc.sh"

[target.aarch64-unknown-linux-gnu]
linker = "./.release/.helpers/zcc.sh"

[target.x86_64-unknown-linux-gnu]
linker = "./.release/.helpers/zcc.sh"
