name: "Release GitHub"
description: "Create a GitHub Release"
inputs:
  version:
    description: "Version to release"
    required: true
runs:
  using: "composite"
  steps:
    - name: Tag current commit
      shell: sh
      env:
        tag: "v${{ inputs.version }}"
      run: |
        git tag "$tag"
    - name: Patch Cargo.toml version
      shell: sh
      env:
        tag: "v${{ inputs.version }}"
      run: |
        version="${tag#v}"
        toml set Cargo.toml package.version "$version" > Cargo.toml.tmp && mv Cargo.toml.tmp Cargo.toml
        cargo update --package "${GITHUB_REPOSITORY#*/}"
    - name: Create aarch64-apple-darwin archive
      shell: sh
      env:
        VERSION: ${{ inputs.version }}
      run: |
        .release/build.sh aarch64-apple-darwin
    - name: Create aarch64-unknown-linux-musl archive
      shell: sh
      env:
        VERSION: ${{ inputs.version }}
      run: |
        .release/build.sh aarch64-unknown-linux-musl
    - name: Create x86_64-unknown-linux-musl archive
      shell: sh
      env:
        VERSION: ${{ inputs.version }}
      run: |
        .release/build.sh x86_64-unknown-linux-musl
    - name: Release
      shell: sh
      env:
        GH_TOKEN: ${{ github.token }}
        version: ${{ inputs.version }}
        title: ${{ inputs.version }}
        tag: "v${{ inputs.version }}"
        repository: ${{ github.event.repository.name }}
      run: |
        git reset --hard && git clean -df
        git push origin "$tag"
        gh release create "$tag" --title="$title" --generate-notes --draft
        gh release upload "$tag" $repository-*.tar.gz
    - name: Apply handwritten release notes
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        tag: "v${{ inputs.version }}"
      run: bash "$GITHUB_ACTION_PATH/release-notes.sh" "$tag"
