name: GitHub Action documentation
permissions: {}
on:
  pull_request:
    paths:
      - ".github/workflows/example.yml"
      - ".github/workflows/wildcard/shellcheck.yml"
      - "**.sh"
      - ".shellcheckrc"
jobs:
  test-example:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Find changes
        id: changes
        uses: anttiharju/find-changes-action@v0.10.5 # handles checkout
      - id: shellcheck
        uses: anttiharju/compare-changes-action@v0
        with:
          workflow: wildcard/shellcheck.yml
          changes: ${{ steps.changes.outputs.array }}
      - if: steps.shellcheck.outputs.changed == 'true'
        name: shellcheck
        run: git ls-files -z '*.sh' | xargs --null shellcheck --color=always
